package golang

import (
	"strings"

	"github.com/68696c6c/capricorn_rnd/utils"
)

// File represents a leaf node in a golang project tree.
type File struct {
	*utils.File
	PKG *Package // this is set when a File is passed to package.AddGoFile()
	// Imports      Imports     `yaml:"imports,omitempty"`
	// InitFunction Function    `yaml:"init_function,omitempty"`
	// Consts       []Const     `yaml:"consts,omitempty"`
	// Vars         []Var       `yaml:"vars,omitempty"`
	// Interfaces   []Interface `yaml:"interfaces,omitempty"`
	// TypeAliases  []Value     `yaml:"type_aliases,omitempty"`
	structs []*Struct
	// Functions    []Function  `yaml:"functions,omitempty"`
}

func NewFile(name string, paths Paths) *File {
	return &File{
		File: utils.NewFile(paths.FilePath, utils.Snake(name), "go"),
	}
}

func (f *File) Render() string {
	lines := []string{
		`// Code generated by "gonad"; DO NOT EDIT.`,
		f.PKG.declaration,
		"",
	}
	for _, s := range f.structs {
		lines = append(lines, string(s.Render()))
	}
	return strings.Join(lines, "\n")
}

func (f *File) AddStruct(s *Struct) {
	f.structs = append(f.structs, s)
}
