package golang

import (
	"strings"

	"github.com/68696c6c/capricorn_rnd/utils"
)

// File represents a leaf node in a golang project tree.
type File struct {
	*utils.File
}

func NewFile(name string, paths Paths) *File {
	return &File{
		File: utils.NewFile(paths.FilePath, utils.Snake(name), "go"),
	}
}

func (f *File) Render() []byte {
	lines := []string{
		"// Code generated by \"gonad\"; DO NOT EDIT.\n",
		// f.pkg.declaration,
		// string(f.imports.Render()),
	}
	return []byte(strings.Join(lines, "\n"))
}
